# Generated by Django 4.2 on 2023-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dastavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DurationField(auto_created=True)),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Tayyorlanmoqda', 'Tayyorlanmoqda'), ('Zakaz_tayyor', 'Zakaz tayyor')], max_length=50)),
            ],
            options={
                'verbose_name': 'Dastavka',
                'verbose_name_plural': 'Dastavka',
                'ordering': ['id'],
            },
        ),
    ]
