# Generated by Django 4.2 on 2023-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dastavka',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
