# Generated by Django 4.2 on 2023-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_dastavka_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dastavka',
            name='date',
            field=models.TimeField(auto_created=True),
        ),
    ]
