# Generated by Django 4.2 on 2023-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dastavka_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveBigIntegerField(default=7)),
                ('student_class', models.PositiveBigIntegerField(choices=[('1-sinf', '1_sinf'), ('2-sinf', '2_sinf'), ('3-sinf', '3_sinf'), ('4-sinf', '4_sinf'), ('5-sinf', '5_sinf'), ('6-sinf', '6_sinf'), ('7-sinf', '7_sinf'), ('8-sinf', '8_sinf'), ('9-sinf', '9_sinf')], max_length=255)),
                ('monday_pay', models.PositiveBigIntegerField(default=1)),
                ('tuesday_pay', models.PositiveBigIntegerField(default=1)),
                ('wednesday_pay', models.PositiveBigIntegerField(default=1)),
                ('thursday_pay', models.PositiveBigIntegerField(default=1)),
                ('friday_pay', models.PositiveBigIntegerField(default=1)),
                ('saturday_pay', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dastavka',
                'verbose_name_plural': 'Dastavka',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='dastavka',
        ),
    ]
