# Generated by Django 4.2 on 2023-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_school_delete_dastavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='student_class',
            field=models.PositiveBigIntegerField(choices=[('1-sinf', '1_sinf'), ('2-sinf', '2_sinf'), ('3-sinf', '3_sinf'), ('4-sinf', '4_sinf'), ('5-sinf', '5_sinf'), ('6-sinf', '6_sinf'), ('7-sinf', '7_sinf'), ('8-sinf', '8_sinf'), ('9-sinf', '9_sinf')]),
        ),
    ]
