# Generated by Django 4.2 on 2023-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_school_options_alter_school_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='student_class',
            field=models.CharField(choices=[('1_sinf', '1-sinf'), ('2_sinf', '2-sinf'), ('3_sinf', '3-sinf'), ('4_sinf', '4-sinf'), ('5_sinf', '5-sinf'), ('6_sinf', '6-sinf'), ('7_sinf', '7-sinf'), ('8_sinf', '8-sinf'), ('9_sinf', '9-sinf')], max_length=255),
        ),
    ]
